### ISSUE TITLE
Chapter 4 - Creating Your Game

### ISSUE THREAD

**Issue by auermich93** [PacktPublishing/CPP-Game-Development-By-Example#1]
Dear author,

you are saying on page 123 (first page of chapter 4): 'Remove all player-related code from the **main.cpp** file.'
However, this file is not present; instead you mean the **source.cpp** file. Also the filename on the github repo should be adjusted accordingly.

On page 128 you are referring to a variable 'm_force' within the update() method, which hasn't been declared anywhere. However, the correct variable is 'm_velocity'. This is just wrong in the book, the repo code works.

**Comment by sonam-packt** [comment]
@auermich93 Thank you for suggesting.
